# Generated by Django 3.0.4 on 2020-04-13 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0004_returnorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='a1.Order'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='a1.Order'),
        ),
    ]
